# Book settings
title: ObjectgeoriÃ«nteerd Programmeren I
author: Hanzehogeschool Groningen
logo: images/logo_1.png
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]
only_build_toc_files: true
jupyter_execute_notebooks: force

latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar: true
  use_repository_button: false
  use_issues_button: false
  use_edit_page_button: false
  navbar_number_sections: false

repository:
  url: https://github.com/misja/OOP1
  path_to_book: ""
  branch: main

sphinx:
  config:
    language: nl
    html_show_copyright: false
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_extra_path: ["build"]

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - amsmath

bibtex_bibfiles:
  - about/references.bib
